package com.lanrelay;
import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.graphics.Color;import android.graphics.Typeface;import android.view.*;import android.widget.*;import java.io.*;import java.net.*;import java.util.*;
public final class MainActivity extends Activity{
 TextView status,url,files;EditText port;final int PICK=7;
 protected void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(Color.rgb(16,23,34));getWindow().setNavigationBarColor(Color.rgb(16,23,34));ui();if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},8);}
 TextView t(String s,int z,boolean bold){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(Color.WHITE);if(bold)x.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return x;}
 LinearLayout.LayoutParams p(int w,int h){return new LinearLayout.LayoutParams(w<0?w:dp(w),h<0?h:dp(h));} int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
 Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
 void ui(){ScrollView sv=new ScrollView(this);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(18),dp(12),dp(18),dp(24));r.setBackgroundColor(Color.rgb(16,23,34));sv.addView(r);r.addView(t("LAN Relay",28,true),p(-1,40));r.addView(t("Offline local HTTP file server. No cloud, accounts, PSN, or telemetry.",15,false),p(-1,48));status=t("Status: stopped",16,true);url=t("URL: —",18,true);r.addView(status,p(-1,40));r.addView(url,p(-1,44));port=new EditText(this);port.setText("8080");port.setInputType(2);port.setTextColor(Color.WHITE);r.addView(port,p(-1,55));Button start=btn("Start server"),stop=btn("Stop server"),add=btn("Add file"),net=btn("Open Wi-Fi / hotspot settings");r.addView(start);r.addView(stop);r.addView(add);r.addView(net);r.addView(t("Served files",20,true),p(-1,44));files=t("",15,false);r.addView(files,p(-1,-2));start.setOnClickListener(v->start());stop.setOnClickListener(v->stop());add.setOnClickListener(v->pick());net.setOnClickListener(v->{try{startActivity(new Intent(Settings.ACTION_WIRELESS_SETTINGS));}catch(Exception e){startActivity(new Intent(Settings.ACTION_SETTINGS));}});setContentView(sv);refresh();}
 void start(){int q;try{q=Integer.parseInt(port.getText().toString());}catch(Exception e){q=8080;}if(q<1024||q>65535){status.setText("Status: invalid port");return;}Intent i=new Intent(this,RelayService.class).putExtra("port",q);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);new Handler().postDelayed(()->{if(RelayService.server!=null&&RelayService.server.isRunning()){status.setText("Status: running");url.setText("URL: http://"+ip()+":"+q+"/");}},500);}
 void stop(){stopService(new Intent(this,RelayService.class));status.setText("Status: stopped");url.setText("URL: —");}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,PICK);}
 protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&c==RESULT_OK&&d!=null)copy(d.getData());}
 void copy(Uri u){try{File root=new File(getFilesDir(),"www");root.mkdirs();String n="file-"+System.currentTimeMillis();String path=u.getPath();if(path!=null&&path.lastIndexOf('/')>=0)n=path.substring(path.lastIndexOf('/')+1);n=n.replace('/','_').replace('\\','_');if(n.isEmpty())n="file";try(InputStream in=getContentResolver().openInputStream(u);OutputStream o=new FileOutputStream(new File(root,n))){byte[]b=new byte[16384];int z;while((z=in.read(b))!=-1)o.write(b,0,z);}refresh();}catch(Exception e){status.setText("Add file failed");}}
 void refresh(){if(files==null)return;File[]a=new File(getFilesDir(),"www").listFiles();StringBuilder s=new StringBuilder();if(a!=null)for(File f:a)if(f.isFile())s.append(f.getName()).append(" ("+f.length()+" B)\n");files.setText(s.length()==0?"No files yet.":s.toString());}
 String ip(){try{Enumeration<NetworkInterface> e=NetworkInterface.getNetworkInterfaces();while(e.hasMoreElements()){NetworkInterface n=e.nextElement();if(!n.isUp()||n.isLoopback())continue;Enumeration<InetAddress>a=n.getInetAddresses();while(a.hasMoreElements()){InetAddress x=a.nextElement();if(x instanceof Inet4Address&&!x.isLoopbackAddress())return x.getHostAddress();}}}catch(Exception ignored){}return"<phone-ip>";}
}
