package com.lanrelay;

import java.io.*;import java.net.*;import java.nio.charset.StandardCharsets;import java.util.*;

public final class RelayServer {
 public interface Listener{void onError(Exception e);} private final File root;private final int port;private final Listener listener;private volatile boolean running;private ServerSocket ss;
 public RelayServer(File root,int port,Listener l){this.root=root;this.port=port;listener=l;}
 public synchronized void start()throws Exception{if(running)return;if(!root.exists()&&!root.mkdirs())throw new IOException("Cannot create server directory");ss=new ServerSocket();ss.setReuseAddress(true);ss.bind(new InetSocketAddress("0.0.0.0",port));running=true;new Thread(()->{while(running)try{Socket s=ss.accept();new Thread(()->handle(s),"relay-client").start();}catch(Exception e){if(running&&listener!=null)listener.onError(e);}},"relay-accept").start();}
 public synchronized void stop(){running=false;try{if(ss!=null)ss.close();}catch(Exception ignored){}ss=null;} public boolean isRunning(){return running;}
 private void handle(Socket s){try(Socket x=s){x.setSoTimeout(10000);BufferedReader r=new BufferedReader(new InputStreamReader(x.getInputStream(),StandardCharsets.US_ASCII));String req=r.readLine();if(req==null)return;String[] a=req.split(" ");if(a.length<2||!(a[0].equals("GET")||a[0].equals("HEAD"))){send(x,405,"Method Not Allowed","text/plain","Method not allowed\n");return;}String line;while((line=r.readLine())!=null&&!line.isEmpty()){}String path=a[1];int q=path.indexOf('?');if(q>=0)path=path.substring(0,q);path=URLDecoder.decode(path,StandardCharsets.UTF_8.name());if(path.equals("/")){send(x,200,"OK","text/html; charset=utf-8",index());return;}if(path.contains("..")||path.contains("\\")){send(x,400,"Bad Request","text/plain","Invalid path\n");return;}File base=root.getCanonicalFile(),f=new File(root,path.substring(1)).getCanonicalFile();String bp=base.getPath(),fp=f.getPath();if(!fp.equals(bp)&&!fp.startsWith(bp+File.separator)){send(x,403,"Forbidden","text/plain","Forbidden\n");return;}if(!f.isFile()){send(x,404,"Not Found","text/plain","Not found\n");return;}try(OutputStream o=x.getOutputStream();InputStream in=new FileInputStream(f)){o.write(("HTTP/1.1 200 OK\r\nContent-Type: "+mime(f.getName())+"\r\nContent-Length: "+f.length()+"\r\nConnection: close\r\n\r\n").getBytes(StandardCharsets.US_ASCII));if(!a[0].equals("HEAD")){byte[]b=new byte[16384];int n;while((n=in.read(b))!=-1)o.write(b,0,n);}o.flush();}}catch(Exception e){if(listener!=null&&running)listener.onError(e);}}
 private String index(){StringBuilder b=new StringBuilder("<!doctype html><meta name=viewport content='width=device-width,initial-scale=1'><title>LAN Relay</title><style>body{font:16px sans-serif;max-width:860px;margin:2em auto;padding:0 1em;background:#101722;color:#f5f7fa}a{color:#71a7ff}li{margin:.7em 0}</style><h1>LAN Relay</h1><ul>");File[]fs=root.listFiles();if(fs!=null){Arrays.sort(fs,Comparator.comparing(File::getName,String.CASE_INSENSITIVE_ORDER));for(File f:fs)if(f.isFile())b.append("<li><a href='/"+esc(f.getName())+"'>"+esc(f.getName())+"</a> ("+f.length()+" bytes)</li>");}b.append("</ul>");return b.toString();}
 private static String esc(String s){return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
 private static void send(Socket s,int c,String r,String m,String body)throws Exception{byte[]d=body.getBytes(StandardCharsets.UTF_8);try(OutputStream o=s.getOutputStream()){o.write(("HTTP/1.1 "+c+" "+r+"\r\nContent-Type: "+m+"\r\nContent-Length: "+d.length+"\r\nConnection: close\r\n\r\n").getBytes(StandardCharsets.US_ASCII));o.write(d);}}
 private static String mime(String n){n=n.toLowerCase(Locale.US);if(n.endsWith(".html")||n.endsWith(".htm"))return"text/html; charset=utf-8";if(n.endsWith(".js"))return"application/javascript; charset=utf-8";if(n.endsWith(".css"))return"text/css; charset=utf-8";if(n.endsWith(".json"))return"application/json; charset=utf-8";if(n.endsWith(".txt"))return"text/plain; charset=utf-8";if(n.endsWith(".mp3"))return"audio/mpeg";if(n.endsWith(".mp4"))return"video/mp4";if(n.endsWith(".png"))return"image/png";if(n.endsWith(".jpg")||n.endsWith(".jpeg"))return"image/jpeg";if(n.endsWith(".zip"))return"application/zip";return"application/octet-stream";}
}
